import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { fontSans, iranSans } from "@/config/fonts";
import clsx from "clsx";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={clsx(
          "font-sans antialiased",
          iranSans.variable,
          locale === "fa" || locale === "ar" ? "font-iransans" : fontSans.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
